/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
	implementation("xml-apis:xml-apis:2.0.2")
	implementation("xerces:xercesImpl:2.12.1")
	implementation("org.jboss.javaee:jboss-jms-api:1.1.0.GA")
	implementation("org.jboss.javaee:jboss-ejb-api-3.0_spec:5.0.2.GA")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.mockito:mockito-core:3.12.4")
}

group = "celeragb"
version = "5.1"
description = "Celera Genome Browser"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks {
    val main = sourceSets.main.get()
    register<Jar>("inclusiveContainer") {
        group = "build"
        dependsOn(build)
        // shouldRunAfter(parent!!.tasks["prepCopyJsBundleToKtor"]) -> This is for incorporating KotlinJS gradle subproject resulting js file.
        manifest {
            attributes["Main-Class"] = "client.gui.application.genome_browser.GenomeBrowser"
        }

        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        from(configurations.compileClasspath.get().files.map { if (it.isDirectory) it else zipTree(it) })
        with(jar.get() as CopySpec)
        archiveBaseName.set("${project.name}-with-dependencies")
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
